//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycats
{
    using System;
    using System.Collections.Generic;
    
    public partial class numberofcat
    {
        public int id { get; set; }
        public string Type { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Number_of_cats { get; set; }
    }
}
